# Generated by Django 6.0.5 on 2026-05-17 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('rank_code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('applicant_date_of_birth', models.DateField(blank=True, null=True)),
                ('application_path', models.CharField(choices=[('FIGHTER', 'Fighter'), ('SOLDIER', 'Soldier')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('intermediate_cleared', 'Intermediate Cleared'), ('enrolled_training', 'Enrolled Training'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='police.department')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('department_join_date', models.DateField()),
                ('is_soldier_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='police.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_rank_personnel', to='police.rank')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='IntermediateClearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_clearings', to='police.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='police.department')),
            ],
            options={
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('duty_status', models.CharField(default='assigned', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments', to='police.department')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='police.personnel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments', to='police.station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='planned', max_length=20)),
                ('decision_made', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignment', to='police.application')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assignments', to='police.department')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('waiting_department_service', 'Waiting 5+ years service'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('requires_5_years_service', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='police.personnel')),
                ('target_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_requests', to='police.rank')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_decisions', to=settings.AUTH_USER_MODEL)),
                ('final_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_ranks', to='police.rank')),
                ('upgrade_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='police.upgraderequest')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='police.personnel')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rank_history', to='police.rank')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='rank_history_end_after_start')],
            },
        ),
    ]
